#!/bin/sh

NEWMAC=`openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/./0/2; s/.$//'`

echo "New generated MAC: ${NEWMAC}"
printf "Reset MAC to this? [y/n] " 
read ser

if [ "$ser" == "y" ]; then
    sudo ifconfig en0 ether $NEWMAC
else
    echo "Aborting.."
fi
